name: Olá Mundo!

on: [push]

jobs: 
  dizer-ola: 
      runs-on: ubuntu-latest
      steps:
        - name: Imprime uma mensagem no console
          run: echo "Olá, Mundo! Está é minha primeira Github Action!"
        - name: Imprime outra mensagem
          run: echo "Até a próxima automação!"
